const API='';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
const token=()=>localStorage.getItem('maxx_token')||'';
const headers=()=>({'content-type':'application/json','authorization':`Bearer ${token()}`});
async function api(path,opt={}){const r=await fetch(path,{cache:'no-store',...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function requireAuth(){if(!token()){location.href='login.html';return false}return true}
function priceFmt(n){n=Number(n);return n<10?n.toFixed(5):n.toLocaleString('en-US',{maximumFractionDigits:2})}
function drawChart(){const c=document.querySelector('canvas');if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,r.width,r.height);let y=r.height*.58;x.strokeStyle='#39d98a';x.lineWidth=2;x.beginPath();for(let i=0;i<110;i++){y+=(Math.sin(i/7)*1.2)+(Math.random()-.5)*10;y=Math.max(30,Math.min(r.height-30,y));const px=i*r.width/109;i?x.lineTo(px,y):x.moveTo(px,y)}x.stroke()}
async function loadMarkets(){const body=document.querySelector('#marketRows');if(!body)return;try{const j=await api('/api/demo/markets');body.innerHTML=j.markets.map(m=>`<tr><td><b>${m.symbol}</b></td><td>${m.assetClass}</td><td>${priceFmt(m.price)}</td><td class="${m.changePct>=0?'green':'red'}">${m.changePct>=0?'+':''}${m.changePct.toFixed(2)}%</td><td><a href="trade.html?symbol=${encodeURIComponent(m.symbol)}">Trade →</a></td></tr>`).join('')}catch(e){body.innerHTML=`<tr><td colspan="5" class="red">${e.message}</td></tr>`}}
async function refreshAccount(){if(!document.querySelector('#accountStats'))return;if(!requireAuth())return;try{const a=await api('/api/demo/account',{headers:headers()});document.querySelector('#balance').textContent=money(a.balance);document.querySelector('#equity').textContent=money(a.equity);document.querySelector('#freeMargin').textContent=money(a.freeMargin);const pl=document.querySelector('#pnl');pl.textContent=(a.unrealizedPnl>=0?'+':'')+money(a.unrealizedPnl);pl.className='big '+(a.unrealizedPnl>=0?'green':'red');renderPositions(a.positions)}catch(e){if(/auth|session/i.test(e.message))location.href='login.html'}}
function renderPositions(rows){const b=document.querySelector('#positions');if(!b)return;b.innerHTML=rows.length?rows.map(p=>{const cur=p.entryPrice;return `<tr><td>${p.symbol}</td><td class="${p.side==='BUY'?'green':'red'}">${p.side}</td><td>${money(p.notional)}</td><td>${priceFmt(p.entryPrice)}</td><td>${p.leverage}×</td><td><button class="mini" onclick="closePosition('${p.id}')">Close</button></td></tr>`}).join(''):'<tr><td colspan="6" class="muted">No open demo positions.</td></tr>'}
async function place(side){if(!requireAuth())return;const symbol=document.querySelector('#symbol').value,notional=Number(document.querySelector('#size').value);try{await api('/api/demo/positions',{method:'POST',headers:headers(),body:JSON.stringify({symbol,side,notional})});await refreshAccount()}catch(e){alert(e.message)}}
async function closePosition(id){try{await api('/api/demo/positions/'+id+'/close',{method:'POST',headers:headers()});await refreshAccount();await loadHistory()}catch(e){alert(e.message)}}
async function loadHistory(){const b=document.querySelector('#historyRows');if(!b)return;if(!requireAuth())return;try{const j=await api('/api/demo/history',{headers:headers()});b.innerHTML=j.positions.length?j.positions.map(p=>`<tr><td>${p.symbol}</td><td class="${p.side==='BUY'?'green':'red'}">${p.side}</td><td>${money(p.notional)}</td><td>${priceFmt(p.entryPrice)}</td><td>${p.exitPrice?priceFmt(p.exitPrice):'—'}</td><td class="${Number(p.realizedPnl||0)>=0?'green':'red'}">${p.status==='CLOSED'?(p.realizedPnl>=0?'+':'')+money(p.realizedPnl):'Open'}</td><td>${new Date(p.openedAt).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="7" class="muted">No demo trades yet.</td></tr>'}catch(e){b.innerHTML=`<tr><td colspan="7" class="red">${e.message}</td></tr>`}}
function initSymbol(){const s=new URLSearchParams(location.search).get('symbol');const el=document.querySelector('#symbol');if(s&&el&&[...el.options].some(o=>o.value===s))el.value=s}
addEventListener('load',()=>{initSymbol();drawChart();loadMarkets();refreshAccount();loadHistory();setInterval(refreshAccount,10000)});addEventListener('resize',drawChart);
