const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n||0));
const KEY='maxx_demo_account_v2';
const PRICES={'EUR/USD':1.18142,'GBP/USD':1.35210,'USD/JPY':147.82,'BTC/USD':112450,'ETH/USD':4188,'AAPL':231.45,'NVDA':178.26};
const CHANGES={'EUR/USD':0.18,'GBP/USD':-0.12,'USD/JPY':0.09,'BTC/USD':1.42,'ETH/USD':0.84,'AAPL':0.55,'NVDA':-0.37};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{balance:10000,positions:[],history:[]}}catch{return {balance:10000,positions:[],history:[]}}}
function save(a){localStorage.setItem(KEY,JSON.stringify(a))}
function requireAuth(){if(!(localStorage.getItem('maxx_token')||sessionStorage.getItem('maxxDemoSession'))){location.href='login.html';return false}return true}
function priceFmt(n){n=Number(n);return n<10?n.toFixed(5):n.toLocaleString('en-US',{maximumFractionDigits:2})}
function drawChart(){const c=document.querySelector('canvas');if(!c)return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,r.width,r.height);let y=r.height*.58;x.strokeStyle='#39d98a';x.lineWidth=2;x.beginPath();for(let i=0;i<110;i++){y+=(Math.sin(i/7)*1.2)+(Math.random()-.5)*10;y=Math.max(30,Math.min(r.height-30,y));const px=i*r.width/109;i?x.lineTo(px,y):x.moveTo(px,y)}x.stroke()}
function loadMarkets(){const body=document.querySelector('#marketRows');if(!body)return;body.innerHTML=Object.keys(PRICES).map((s,i)=>`<tr><td><b>${s}</b></td><td>${i<3?'Forex':i<5?'Crypto':'Stock'}</td><td>${priceFmt(PRICES[s])}</td><td class="${CHANGES[s]>=0?'green':'red'}">${CHANGES[s]>=0?'+':''}${CHANGES[s].toFixed(2)}%</td><td><a href="trade.html?symbol=${encodeURIComponent(s)}">Trade →</a></td></tr>`).join('')}
function refreshAccount(){if(!document.querySelector('#accountStats'))return;if(!requireAuth())return;const a=load();const margin=a.positions.reduce((s,p)=>s+p.notional/p.leverage,0);document.querySelector('#balance').textContent=money(a.balance);document.querySelector('#equity').textContent=money(a.balance);document.querySelector('#freeMargin').textContent=money(Math.max(0,a.balance-margin));const pl=document.querySelector('#pnl');pl.textContent=money(0);pl.className='big green';renderPositions(a.positions)}
function renderPositions(rows){const b=document.querySelector('#positions');if(!b)return;b.innerHTML=rows.length?rows.map(p=>`<tr><td>${p.symbol}</td><td class="${p.side==='BUY'?'green':'red'}">${p.side}</td><td>${money(p.notional)}</td><td>${priceFmt(p.entryPrice)}</td><td>${p.leverage}×</td><td><button class="mini" onclick="closePosition('${p.id}')">Close</button></td></tr>`).join(''):'<tr><td colspan="6" class="muted">No open demo positions.</td></tr>'}
function place(side){if(!requireAuth())return;const symbol=document.querySelector('#symbol').value,notional=Number(document.querySelector('#size').value);if(!Number.isFinite(notional)||notional<10)return alert('Enter a demo position size of at least $10.');const a=load(),margin=notional/20;if(margin>a.balance)return alert('Not enough demo free margin.');a.positions.push({id:'p'+Date.now(),symbol,side,notional,entryPrice:PRICES[symbol]||1,leverage:20,openedAt:new Date().toISOString(),status:'OPEN'});save(a);refreshAccount()}
function closePosition(id){const a=load(),i=a.positions.findIndex(p=>p.id===id);if(i<0)return;const p=a.positions.splice(i,1)[0];p.exitPrice=p.entryPrice;p.realizedPnl=0;p.status='CLOSED';p.closedAt=new Date().toISOString();a.history.unshift(p);save(a);refreshAccount();loadHistory()}
function loadHistory(){const b=document.querySelector('#historyRows');if(!b)return;if(!requireAuth())return;const rows=load().history;b.innerHTML=rows.length?rows.map(p=>`<tr><td>${p.symbol}</td><td class="${p.side==='BUY'?'green':'red'}">${p.side}</td><td>${money(p.notional)}</td><td>${priceFmt(p.entryPrice)}</td><td>${priceFmt(p.exitPrice)}</td><td class="green">${money(p.realizedPnl)}</td><td>${new Date(p.openedAt).toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="7" class="muted">No demo trades yet.</td></tr>'}
function initSymbol(){const s=new URLSearchParams(location.search).get('symbol'),el=document.querySelector('#symbol');if(s&&el&&[...el.options].some(o=>o.value===s))el.value=s}
addEventListener('load',()=>{initSymbol();drawChart();loadMarkets();refreshAccount();loadHistory()});addEventListener('resize',drawChart);
